apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.db.type }}
  name: {{ .Values.db.type }}
  namespace: {{ template "name" . }}
spec:
  type: {{ .Values.dbservice.type }}
  ports:
  - name: {{ .Values.dbservice.name }}
    port: {{ .Values.dbservice.ports.port }}
    targetPort: {{ .Values.dbservice.ports.Port }}
  selector:
    app: {{ .Values.db.type }}
  
