apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.result.name }}
  name: {{ .Values.app.result.name }}
  namespace: {{ template "name" . }}
spec:
  type: {{ .Values.app.result.service.type }}
  ports:
  - name: {{ .Values.app.result.name }}-service
    port: {{ .Values.app.result.service.ports.port }}
    targetPort: {{ .Values.app.result.service.ports.targetPort }}
    nodePort: {{ .Values.app.result.service.ports.nodePort }}
  selector:
    app: {{ .Values.app.result.name }}
